
needed_packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - awscli

docker_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
